# Generated by Django 5.0.6 on 2024-05-23 01:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gathering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('material_name', models.TextField()),
                ('material_type', models.TextField()),
                ('material_description', models.TextField()),
                ('material_state', models.TextField()),
                ('location_street', models.TextField()),
                ('location_city', models.TextField()),
                ('location_state', models.TextField()),
                ('location_country', models.TextField()),
                ('location_number', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gatherings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
